//! Component composition — generates `.icss` rules from semantic tokens + dimensions.

use crate::engine::dims::DimTokens;
use crate::engine::semantic::{SemanticColors, SurfaceFamily};

/// Emit CSS custom properties for a complete surface family.
fn emit_surface_family(out: &mut String, prefix: &str, family: &SurfaceFamily) {
    css_var(out, &format!("{prefix}-s0"), &family.s0);
    css_var(out, &format!("{prefix}-s1"), &family.s1);
    css_var(out, &format!("{prefix}-s2"), &family.s2);
    css_var(out, &format!("{prefix}-s3"), &family.s3);
    css_var(out, &format!("{prefix}-s4"), &family.s4);
    css_var(out, &format!("on-{prefix}"), &family.text);
    css_var(out, &format!("on-{prefix}-default"), &family.text_default);
    css_var(out, &format!("on-{prefix}-soft"), &family.text_soft);
    css_var(out, &format!("on-{prefix}-dim"), &family.text_dim);
    css_var(out, &format!("on-{prefix}-muted"), &family.text_muted);
    css_var(out, &format!("on-{prefix}-faint"), &family.text_faint);
    css_var(out, &format!("on-{prefix}-disabled"), &family.text_disabled);
    emit_family_outlines(out, prefix, family);
}

/// Emit outline custom properties for a surface family.
///
/// Named `--outline-{family}-{level}`, so a chromatic family's set reads as a
/// sibling of the neutral page set. The neutral family is skipped here because
/// `compose_icss` already emits its six levels under the bare `--outline-*`
/// names that components reference.
fn emit_family_outlines(out: &mut String, prefix: &str, family: &SurfaceFamily) {
    let Some(name) = prefix.strip_prefix("surface-") else {
        return;
    };
    let o = &family.outlines;
    css_var(out, &format!("outline-{name}-subtle"), &o.subtle);
    css_var(out, &format!("outline-{name}-soft"), &o.soft);
    css_var(out, &format!("outline-{name}-middle"), &o.middle);
    css_var(out, &format!("outline-{name}-strong"), &o.strong);
    css_var(out, &format!("outline-{name}-heavy"), &o.heavy);
    css_var(out, &format!("outline-{name}-solid"), &o.solid);
}

/// Emit swatch CSS classes for a surface family.
fn emit_family_swatches(out: &mut String, prefix: &str, r50: &str) {
    let swatch = |out: &mut String, cls: &str, bg: &str| {
        rule(
            out,
            cls,
            &[("background-color", bg), ("border-radius", r50)],
        );
    };
    for i in 0..=4 {
        swatch(
            out,
            &format!(".sw-{prefix}-{i}"),
            &format!("var(--{prefix}-s{i})"),
        );
    }
    swatch(
        out,
        &format!(".sw-on-{prefix}"),
        &format!("var(--on-{prefix})"),
    );
    swatch(
        out,
        &format!(".sw-on-{prefix}-default"),
        &format!("var(--on-{prefix}-default)"),
    );
    swatch(
        out,
        &format!(".sw-on-{prefix}-soft"),
        &format!("var(--on-{prefix}-soft)"),
    );
    swatch(
        out,
        &format!(".sw-on-{prefix}-dim"),
        &format!("var(--on-{prefix}-dim)"),
    );
    swatch(
        out,
        &format!(".sw-on-{prefix}-muted"),
        &format!("var(--on-{prefix}-muted)"),
    );
    swatch(
        out,
        &format!(".sw-on-{prefix}-faint"),
        &format!("var(--on-{prefix}-faint)"),
    );
    swatch(
        out,
        &format!(".sw-on-{prefix}-disabled"),
        &format!("var(--on-{prefix}-disabled)"),
    );
    // Outline swatches, so the primitives page can show a family's own
    // borders next to its surfaces and text.
    if let Some(name) = prefix.strip_prefix("surface-") {
        for level in ["subtle", "soft", "middle", "strong", "heavy", "solid"] {
            swatch(
                out,
                &format!(".sw-outline-{name}-{level}"),
                &format!("var(--outline-{name}-{level})"),
            );
        }
    }
}

/// Generate the full `.icss` theme string.
///
/// `scale_colors` is the closest-path scale derived from the 4 chromatic
/// anchors (P/S/T/Q) at step 50. It is emitted as `--scale-colors-0` …
/// `--scale-colors-{N-1}` so consumers can reference a stable tint set
/// for things like per-device tile backgrounds.
pub fn compose_icss(colors: &SemanticColors, dims: &DimTokens, scale_colors: &[String]) -> String {
    let mut out = String::with_capacity(8192);

    // ── :root variables (colors + spacing tokens) ──
    out.push_str("/* Generated by icss */\n\n:root {\n");

    // Neutral surface
    emit_surface_family(&mut out, "surface", &colors.surface);
    css_var(&mut out, "surface-s5", &colors.surface_s5);

    // Legacy aliases for neutral text (used by components as --text, --text-default, etc.)
    css_var(&mut out, "text", &colors.surface.text);
    css_var(&mut out, "text-default", &colors.surface.text_default);
    css_var(&mut out, "text-soft", &colors.surface.text_soft);
    css_var(&mut out, "text-dim", &colors.surface.text_dim);
    css_var(&mut out, "text-muted", &colors.surface.text_muted);
    css_var(&mut out, "text-faint", &colors.surface.text_faint);
    css_var(&mut out, "text-disabled", &colors.surface.text_disabled);

    // Outlines
    css_var(&mut out, "outline-subtle", &colors.outline_subtle_alpha);
    css_var(&mut out, "outline-soft", &colors.outline_soft_alpha);
    css_var(&mut out, "outline-middle", &colors.outline_middle);
    css_var(&mut out, "outline-strong", &colors.outline_strong);
    css_var(&mut out, "outline-heavy", &colors.outline_heavy);
    css_var(&mut out, "outline-solid", &colors.outline_solid);
    css_var(&mut out, "outline-subtle-hex", &colors.outline_subtle);
    css_var(&mut out, "outline-soft-hex", &colors.outline_soft);

    // Tint / dark-tint / black families
    emit_surface_family(&mut out, "surface-tint", &colors.tint);
    emit_surface_family(&mut out, "surface-dark-tint", &colors.dark_tint);
    emit_surface_family(&mut out, "surface-black", &colors.black);

    // Chromatic surface families
    emit_surface_family(&mut out, "surface-primary", &colors.primary);
    emit_surface_family(
        &mut out,
        "surface-primary-container",
        &colors.primary_container,
    );
    emit_surface_family(&mut out, "surface-secondary", &colors.secondary);
    emit_surface_family(
        &mut out,
        "surface-secondary-container",
        &colors.secondary_container,
    );
    emit_surface_family(&mut out, "surface-tertiary", &colors.tertiary);
    emit_surface_family(
        &mut out,
        "surface-tertiary-container",
        &colors.tertiary_container,
    );
    emit_surface_family(&mut out, "surface-quaternary", &colors.quaternary);
    emit_surface_family(
        &mut out,
        "surface-quaternary-container",
        &colors.quaternary_container,
    );

    // Signal surface families
    emit_surface_family(&mut out, "surface-success", &colors.success);
    emit_surface_family(
        &mut out,
        "surface-success-container",
        &colors.success_container,
    );
    emit_surface_family(&mut out, "surface-danger", &colors.danger);
    emit_surface_family(
        &mut out,
        "surface-danger-container",
        &colors.danger_container,
    );
    emit_surface_family(&mut out, "surface-warning", &colors.warning);
    emit_surface_family(
        &mut out,
        "surface-warning-container",
        &colors.warning_container,
    );

    // Link accent (single step, not a full surface family)
    css_var(&mut out, "surface-link-s0", &colors.on_surface_link);

    // Shadows
    css_var(&mut out, "shadow", &colors.shadow_color);
    css_var(&mut out, "shadow-medium", &colors.shadow_color_medium);
    css_var(&mut out, "shadow-soft", &colors.shadow_color_soft);

    // Closest-path scale (20 chromatic anchors at step 50) — exposed so
    // consumers can pick a stable tint by index (e.g. per-device tiles).
    css_var(
        &mut out,
        "scale-colors-count",
        &scale_colors.len().to_string(),
    );
    for (i, hex) in scale_colors.iter().enumerate() {
        css_var(&mut out, &format!("scale-colors-{i}"), hex);
    }

    // ── Dimensional tokens (spacing, sizing, radius, typography) ──
    // Exported as CSS vars so hand-written .icss can use them, and so the
    // generated rules below read as semantic intent rather than magic
    // numbers. They all derive from `increment` / `font_increment` /
    // `radius_factor`. Editing those three regenerates everything.
    css_var(&mut out, "space-25", &px(dims.space_25));
    css_var(&mut out, "space-50", &px(dims.space_50));
    css_var(&mut out, "space-75", &px(dims.space_75));
    css_var(&mut out, "space-100", &px(dims.space_100));
    css_var(&mut out, "space-150", &px(dims.space_150));
    css_var(&mut out, "space-200", &px(dims.space_200));
    css_var(&mut out, "space-250", &px(dims.space_250));
    css_var(&mut out, "space-300", &px(dims.space_300));
    css_var(&mut out, "space-400", &px(dims.space_400));
    css_var(&mut out, "space-500", &px(dims.space_500));

    css_var(&mut out, "size-100", &px(dims.size_100));
    css_var(&mut out, "size-150", &px(dims.size_150));
    css_var(&mut out, "size-200", &px(dims.size_200));
    css_var(&mut out, "size-250", &px(dims.size_250));
    css_var(&mut out, "size-300", &px(dims.size_300));
    css_var(&mut out, "size-400", &px(dims.size_400));
    css_var(&mut out, "size-500", &px(dims.size_500));

    css_var(&mut out, "radius-25", &px(dims.radius_25));
    css_var(&mut out, "radius-50", &px(dims.radius_50));
    css_var(&mut out, "radius-75", &px(dims.radius_75));
    css_var(&mut out, "radius-100", &px(dims.radius_100));
    css_var(&mut out, "radius-150", &px(dims.radius_150));
    css_var(&mut out, "radius-200", &px(dims.radius_200));
    css_var(&mut out, "radius-infinite", &px(dims.radius_infinite));

    css_var(&mut out, "font-body-micro", &px(dims.font_body_micro));
    css_var(&mut out, "font-body-small", &px(dims.font_body_small));
    css_var(&mut out, "font-body-medium", &px(dims.font_body_medium));
    css_var(&mut out, "font-body-large", &px(dims.font_body_large));
    css_var(&mut out, "font-label-micro", &px(dims.font_label_micro));
    css_var(&mut out, "font-label-small", &px(dims.font_label_small));
    css_var(&mut out, "font-label-medium", &px(dims.font_label_medium));
    css_var(&mut out, "font-label-large", &px(dims.font_label_large));
    css_var(&mut out, "font-title-small", &px(dims.font_title_small));
    css_var(&mut out, "font-title-medium", &px(dims.font_title_medium));
    css_var(&mut out, "font-title-large", &px(dims.font_title_large));
    css_var(
        &mut out,
        "font-headline-micro",
        &px(dims.font_headline_micro),
    );
    css_var(
        &mut out,
        "font-headline-small",
        &px(dims.font_headline_small),
    );
    css_var(
        &mut out,
        "font-headline-medium",
        &px(dims.font_headline_medium),
    );
    css_var(
        &mut out,
        "font-headline-large",
        &px(dims.font_headline_large),
    );
    css_var(
        &mut out,
        "font-headline-xlarge",
        &px(dims.font_headline_xlarge),
    );

    out.push_str("}\n\n");

    // ── Page ──
    rule(
        &mut out,
        ".page",
        &[
            ("background-color", "var(--surface-s0)"),
            ("color", "var(--text-default)"),
        ],
    );

    // ── Section container ──
    rule(
        &mut out,
        ".section",
        &[
            ("background-color", "var(--surface-s1)"),
            ("border-radius", &px(dims.radius_150)),
        ],
    );

    // ── Divider ──
    rule(&mut out, ".divider", &[("color", "var(--outline-subtle)")]);

    // ── Component sizing (shared across buttons, inputs, pick-lists) ──
    // Only padding/font-size/gap/min-width live here. Per-size border-radius
    // is emitted later as compound selectors (`.button.sz-md`, etc.) so it
    // doesn't clash with component defaults at equal specificity.
    rule(
        &mut out,
        ".sz-md",
        &[
            ("padding-v", "var(--space-100)"),
            ("padding-h", "var(--space-200)"),
            ("font-size", "var(--font-label-large)"),
            ("min-width", "100px"),
            ("gap", "var(--space-75)"),
        ],
    );
    rule(
        &mut out,
        ".sz-sm",
        &[
            ("padding-v", "var(--space-75)"),
            ("padding-h", "var(--space-150)"),
            ("font-size", "var(--font-label-medium)"),
            ("min-width", "80px"),
            ("gap", "var(--space-75)"),
        ],
    );
    rule(
        &mut out,
        ".sz-xs",
        &[
            ("padding-v", "var(--space-50)"),
            ("padding-h", "var(--space-100)"),
            ("font-size", "var(--font-label-small)"),
            ("gap", "var(--space-50)"),
        ],
    );

    // ── Buttons ──
    rule(
        &mut out,
        ".button",
        &[("border-radius", &px(dims.radius_100))],
    );

    // Primary variant
    rule(
        &mut out,
        ".primary",
        &[
            ("background-color", "var(--surface-primary-s0)"),
            ("color", "var(--on-surface-primary-default)"),
            ("accent-color", "var(--on-surface-primary-soft)"),
            ("border-width", "1px"),
            ("border-color", "var(--surface-primary-s2)"),
            (
                "box-shadow",
                &format!("0 1px {} var(--shadow-soft)", px(dims.space_25)),
            ),
        ],
    );
    rule(
        &mut out,
        ".primary:hover",
        &[
            ("background-color", "var(--surface-primary-s2)"),
            ("color", "var(--on-surface-primary)"),
            ("accent-color", "var(--on-surface-primary-default)"),
            ("border-color", "var(--surface-primary-s3)"),
            (
                "box-shadow",
                &format!("0 1px {} var(--shadow-soft)", px(dims.space_50)),
            ),
        ],
    );
    rule(
        &mut out,
        ".primary:active",
        &[
            ("background-color", "var(--surface-primary-s4)"),
            ("border-color", "var(--surface-primary-s4)"),
        ],
    );
    rule(
        &mut out,
        ".primary:disabled",
        &[("opacity", "0.5"), ("box-shadow", "none")],
    );

    // Success variant
    rule(
        &mut out,
        ".success",
        &[
            ("background-color", "var(--surface-success-s0)"),
            ("color", "var(--on-surface-success-default)"),
            ("accent-color", "var(--on-surface-success-soft)"),
            ("border-width", "1px"),
            ("border-color", "var(--surface-success-s2)"),
            (
                "box-shadow",
                &format!("0 1px {} var(--shadow-soft)", px(dims.space_25)),
            ),
        ],
    );
    rule(
        &mut out,
        ".success:hover",
        &[
            ("background-color", "var(--surface-success-s2)"),
            ("color", "var(--on-surface-success)"),
            ("accent-color", "var(--on-surface-success-default)"),
            ("border-color", "var(--surface-success-s3)"),
            (
                "box-shadow",
                &format!("0 1px {} var(--shadow-soft)", px(dims.space_50)),
            ),
        ],
    );
    rule(
        &mut out,
        ".success:active",
        &[
            ("background-color", "var(--surface-success-s4)"),
            ("border-color", "var(--surface-success-s4)"),
        ],
    );
    rule(
        &mut out,
        ".success:disabled",
        &[("opacity", "0.5"), ("box-shadow", "none")],
    );

    // Danger variant
    rule(
        &mut out,
        ".danger",
        &[
            ("background-color", "var(--surface-danger-s0)"),
            ("color", "var(--on-surface-danger-default)"),
            ("accent-color", "var(--on-surface-danger-soft)"),
            ("border-width", "1px"),
            ("border-color", "var(--surface-danger-s2)"),
            (
                "box-shadow",
                &format!("0 1px {} var(--shadow-soft)", px(dims.space_25)),
            ),
        ],
    );
    rule(
        &mut out,
        ".danger:hover",
        &[
            ("background-color", "var(--surface-danger-s2)"),
            ("color", "var(--on-surface-danger)"),
            ("accent-color", "var(--on-surface-danger-default)"),
            ("border-color", "var(--surface-danger-s3)"),
            (
                "box-shadow",
                &format!("0 1px {} var(--shadow-soft)", px(dims.space_50)),
            ),
        ],
    );
    rule(
        &mut out,
        ".danger:active",
        &[
            ("background-color", "var(--surface-danger-s4)"),
            ("border-color", "var(--surface-danger-s4)"),
        ],
    );
    rule(
        &mut out,
        ".danger:disabled",
        &[("opacity", "0.5"), ("box-shadow", "none")],
    );

    // Default variant — raised surface fill + outline + shadow
    rule(
        &mut out,
        ".default",
        &[
            ("background-color", "var(--surface-s2)"),
            ("color", "var(--text-soft)"),
            ("accent-color", "var(--text-muted)"),
            ("border-width", "1px"),
            ("border-color", "var(--outline-soft)"),
            (
                "box-shadow",
                &format!("0 1px {} var(--shadow-soft)", px(dims.space_25)),
            ),
        ],
    );
    rule(
        &mut out,
        ".default:hover",
        &[
            ("background-color", "var(--surface-s3)"),
            ("color", "var(--text-default)"),
            ("accent-color", "var(--text-default)"),
            ("border-color", "var(--outline-middle)"),
            (
                "box-shadow",
                &format!("0 1px {} var(--shadow-soft)", px(dims.space_50)),
            ),
        ],
    );
    rule(
        &mut out,
        ".default:active",
        &[
            ("background-color", "var(--surface-s4)"),
            ("box-shadow", "none"),
        ],
    );
    rule(
        &mut out,
        ".default:disabled",
        &[("opacity", "0.5"), ("box-shadow", "none")],
    );

    // Ghost variant — no border, transparent background
    rule(
        &mut out,
        ".ghost",
        &[
            ("background-color", "transparent"),
            ("color", "var(--text-soft)"),
            ("accent-color", "var(--text-muted)"),
            ("border-radius", &px(dims.radius_150)),
        ],
    );
    rule(
        &mut out,
        ".ghost:hover",
        &[
            ("background-color", "var(--outline-subtle)"),
            ("color", "var(--text-default)"),
            ("accent-color", "var(--text-default)"),
        ],
    );
    rule(
        &mut out,
        ".ghost:active",
        &[("background-color", "var(--outline-soft)")],
    );
    rule(
        &mut out,
        ".ghost:disabled",
        &[("background-color", "transparent"), ("opacity", "0.5")],
    );

    // Outlined variant — transparent + border
    rule(
        &mut out,
        ".outlined",
        &[
            ("background-color", "transparent"),
            ("color", "var(--text-soft)"),
            ("accent-color", "var(--text-muted)"),
            ("border-width", "1px"),
            ("border-color", "var(--outline-soft)"),
        ],
    );
    rule(
        &mut out,
        ".outlined:hover",
        &[
            ("background-color", "var(--outline-subtle)"),
            ("color", "var(--text-default)"),
            ("accent-color", "var(--text-default)"),
            ("border-color", "var(--outline-middle)"),
        ],
    );
    rule(
        &mut out,
        ".outlined:active",
        &[("background-color", "var(--outline-soft)")],
    );
    rule(
        &mut out,
        ".outlined:disabled",
        &[("background-color", "transparent"), ("opacity", "0.5")],
    );

    // Shape modifiers — size-keyed border radius (medium = base .button r-100)
    rule(
        &mut out,
        ".small",
        &[("border-radius", &px(dims.radius_75))],
    );
    rule(&mut out, ".tiny", &[("border-radius", &px(dims.radius_50))]);
    rule(
        &mut out,
        ".pill",
        &[("border-radius", &px(dims.radius_infinite))],
    );
    rule(
        &mut out,
        ".round",
        &[("border-radius", &px(dims.radius_infinite))],
    );

    // ── Text Inputs ──
    rule(
        &mut out,
        ".input",
        &[
            ("background-color", "var(--surface-s1)"),
            ("color", "var(--text-default)"),
            ("border-radius", &px(dims.radius_75)),
            ("border-width", "1px"),
            ("border-color", "var(--outline-soft)"),
            ("placeholder-color", "var(--text-disabled)"),
        ],
    );
    rule(
        &mut out,
        ".input:hover",
        &[
            ("background-color", "var(--surface-s1)"),
            ("border-color", "var(--outline-middle)"),
        ],
    );
    rule(
        &mut out,
        ".input:focus",
        &[
            ("background-color", "var(--surface-s0)"),
            ("border-color", "var(--surface-primary-s0)"),
        ],
    );
    rule(&mut out, ".input:disabled", &[("opacity", "0.5")]);
    rule(
        &mut out,
        ".input.error",
        &[("border-color", "var(--surface-danger-s0)")],
    );
    rule(
        &mut out,
        ".input.error:focus",
        &[("border-color", "var(--surface-danger-s0)")],
    );

    // ── Checkboxes ──
    rule(
        &mut out,
        ".checkbox",
        &[
            ("background-color", "var(--outline-subtle)"),
            ("accent-color", "var(--text-default)"),
            ("border-width", "1px"),
            ("border-color", "var(--outline-soft)"),
            ("border-radius", &px(dims.radius_50)),
            ("color", "var(--text-default)"),
        ],
    );
    rule(
        &mut out,
        ".checkbox:hover",
        &[("border-color", "var(--outline-middle)")],
    );
    rule(
        &mut out,
        ".checkbox:checked",
        &[
            ("background-color", "var(--surface-primary-s0)"),
            ("accent-color", "var(--on-surface-primary)"),
            ("border-color", "var(--surface-primary-s0)"),
        ],
    );
    // Read-only / informational checkbox — no on_toggle wired. Iced reports
    // these as Status::Disabled, so the :disabled pseudo styles them muted
    // to make their non-interactive nature obvious.
    rule(
        &mut out,
        ".checkbox:disabled",
        &[("opacity", "0.5"), ("color", "var(--text-soft)")],
    );

    // ── Togglers ──
    // background-color = track, accent-color = knob, color = label text.
    // Off: disabled-text knob on muted track (low emphasis, not mid-tone).
    // On: brand-tinted track with light-on-primary knob.
    rule(
        &mut out,
        ".toggle",
        &[
            ("background-color", "var(--outline-soft)"),
            ("accent-color", "var(--text-disabled)"),
            ("color", "var(--text-default)"),
            ("border-width", "0"),
        ],
    );
    rule(
        &mut out,
        ".toggle:hover",
        &[("background-color", "var(--outline-middle)")],
    );
    rule(
        &mut out,
        ".toggle:checked",
        &[
            ("background-color", "var(--surface-primary-s0)"),
            ("accent-color", "var(--on-surface-primary)"),
            ("color", "var(--text-default)"),
        ],
    );

    // ── Radios ──
    rule(
        &mut out,
        ".radio",
        &[
            ("background-color", "transparent"),
            ("accent-color", "var(--text-default)"),
            ("border-width", "1px"),
            ("border-color", "var(--outline-soft)"),
            ("color", "var(--text-default)"),
        ],
    );
    rule(
        &mut out,
        ".radio:hover",
        &[("border-color", "var(--outline-middle)")],
    );
    rule(
        &mut out,
        ".radio:checked",
        &[
            ("accent-color", "var(--surface-primary-s0)"),
            ("border-color", "var(--surface-primary-s0)"),
        ],
    );

    // ── Sliders ──
    rule(
        &mut out,
        ".slider",
        &[
            ("background-color", "var(--outline-subtle)"),
            ("accent-color", "var(--surface-primary-s0)"),
        ],
    );
    rule(
        &mut out,
        ".slider:hover",
        &[("accent-color", "var(--surface-primary-s1)")],
    );

    // ── Progress Bars ──
    rule(
        &mut out,
        ".progress",
        &[
            ("background-color", "var(--outline-subtle)"),
            ("accent-color", "var(--surface-primary-s0)"),
            ("border-radius", &px(dims.radius_50)),
        ],
    );
    rule(
        &mut out,
        ".progress.success",
        &[("accent-color", "var(--surface-success-s0)")],
    );
    rule(
        &mut out,
        ".progress.danger",
        &[("accent-color", "var(--surface-danger-s0)")],
    );
    rule(
        &mut out,
        ".progress.warning",
        &[("accent-color", "var(--surface-warning-s0)")],
    );

    // ── Pick List ──
    rule(
        &mut out,
        ".select",
        &[
            ("background-color", "var(--surface-s2)"),
            ("color", "var(--text-default)"),
            ("placeholder-color", "var(--text-disabled)"),
            ("accent-color", "var(--text-soft)"),
            ("border-radius", &px(dims.radius_75)),
            ("border-width", "1px"),
            ("border-color", "var(--outline-soft)"),
        ],
    );
    rule(
        &mut out,
        ".select:hover",
        &[("border-color", "var(--outline-middle)")],
    );
    rule(&mut out, ".select:disabled", &[("opacity", "0.5")]);

    // ── Pick List Menu (dropdown overlay) ──
    // Shadow kept small (no offset, half blur) — wgpu renders large blurs
    // as a hard solid band on Windows, which read as a black frame around
    // the popup. Border carries the visual edge instead.
    rule(
        &mut out,
        ".select-menu",
        &[
            ("background-color", "var(--surface-s2)"),
            ("color", "var(--text-default)"),
            ("accent-color", "var(--on-surface-primary)"),
            ("border-color", "var(--surface-primary-s0)"),
            ("border-radius", &px(dims.radius_75)),
            (
                "box-shadow",
                &format!("0 0 {} var(--shadow-soft)", px(dims.space_75)),
            ),
        ],
    );

    // ── Tooltip ──
    rule(
        &mut out,
        ".tooltip",
        &[
            ("background-color", "var(--surface-black-s0)"),
            ("color", "var(--on-surface-black)"),
            ("border-radius", &px(dims.radius_50)),
            (
                "box-shadow",
                &format!(
                    "0 {} {} var(--shadow-soft)",
                    px(dims.space_25),
                    px(dims.space_75)
                ),
            ),
        ],
    );

    // ── Toasts ──
    // Default toast: surface-s0 background, sp-200 padding, sp-50 text gap, rounded, elevated.
    rule(
        &mut out,
        ".toast",
        &[
            ("background-color", "var(--surface-s0)"),
            ("color", "var(--text-default)"),
            ("border-radius", &px(dims.radius_100)),
            ("padding-v", &px(dims.space_200)),
            ("padding-h", &px(dims.space_200)),
            ("gap", &px(dims.space_50)),
            (
                "box-shadow",
                &format!(
                    "0 {} {} var(--shadow-medium)",
                    px(dims.space_50),
                    px(dims.space_100)
                ),
            ),
        ],
    );
    // Highlighted toast: primary surface background with on-primary text.
    rule(
        &mut out,
        ".toast-primary",
        &[
            ("background-color", "var(--surface-primary-s0)"),
            ("color", "var(--on-surface-primary-default)"),
            ("border-radius", &px(dims.radius_100)),
            ("padding-v", &px(dims.space_200)),
            ("padding-h", &px(dims.space_200)),
            ("gap", &px(dims.space_50)),
            (
                "box-shadow",
                &format!(
                    "0 {} {} var(--shadow-medium)",
                    px(dims.space_50),
                    px(dims.space_100)
                ),
            ),
        ],
    );
    // Secondary toast: secondary surface background with on-secondary text.
    rule(
        &mut out,
        ".toast-secondary",
        &[
            ("background-color", "var(--surface-secondary-s0)"),
            ("color", "var(--on-surface-secondary-default)"),
            ("border-radius", &px(dims.radius_100)),
            ("padding-v", &px(dims.space_200)),
            ("padding-h", &px(dims.space_200)),
            ("gap", &px(dims.space_50)),
            (
                "box-shadow",
                &format!(
                    "0 {} {} var(--shadow-medium)",
                    px(dims.space_50),
                    px(dims.space_100)
                ),
            ),
        ],
    );
    // Tertiary toast: tertiary surface background with on-tertiary text.
    rule(
        &mut out,
        ".toast-tertiary",
        &[
            ("background-color", "var(--surface-tertiary-s0)"),
            ("color", "var(--on-surface-tertiary-default)"),
            ("border-radius", &px(dims.radius_100)),
            ("padding-v", &px(dims.space_200)),
            ("padding-h", &px(dims.space_200)),
            ("gap", &px(dims.space_50)),
            (
                "box-shadow",
                &format!(
                    "0 {} {} var(--shadow-medium)",
                    px(dims.space_50),
                    px(dims.space_100)
                ),
            ),
        ],
    );

    // Ghost button for dark/colored surfaces — opacity-based instead of color-scale.
    // Normal: white 60% alpha. Hover: white 80%. Active: white 40%.
    rule(
        &mut out,
        ".ghost-overlay",
        &[
            ("background-color", "transparent"),
            ("color", "rgba(255,255,255,0.6)"),
            ("border-radius", &px(dims.radius_100)),
        ],
    );
    rule(
        &mut out,
        ".ghost-overlay:hover",
        &[
            ("background-color", "rgba(255,255,255,0.1)"),
            ("color", "rgba(255,255,255,0.8)"),
        ],
    );
    rule(
        &mut out,
        ".ghost-overlay:active",
        &[
            ("background-color", "rgba(255,255,255,0.05)"),
            ("color", "rgba(255,255,255,0.4)"),
        ],
    );
    rule(&mut out, ".ghost-overlay:disabled", &[("opacity", "0.3")]);

    // ── Text Editor ──
    rule(
        &mut out,
        ".editor",
        &[
            ("background-color", "var(--outline-subtle)"),
            ("color", "var(--text-default)"),
            ("border-radius", &px(dims.radius_75)),
            ("border-width", "1px"),
            ("border-color", "var(--outline-soft)"),
            ("placeholder-color", "var(--text-disabled)"),
        ],
    );
    rule(
        &mut out,
        ".editor:hover",
        &[("border-color", "var(--outline-middle)")],
    );
    rule(
        &mut out,
        ".editor:focus",
        &[("border-color", "var(--surface-primary-s0)")],
    );

    // ── Scrollable ──
    rule(
        &mut out,
        ".scroll",
        &[
            ("background-color", "transparent"),
            ("accent-color", "var(--outline-soft)"),
            ("border-radius", &px(dims.radius_50)),
        ],
    );

    // ── Tile Grid ──
    rule(
        &mut out,
        ".tile",
        &[
            ("background-color", "var(--surface-s1)"),
            ("color", "var(--text-default)"),
            ("border-radius", &px(dims.radius_150)),
            ("border-width", "1px"),
            ("border-color", "var(--outline-subtle)"),
        ],
    );
    rule(
        &mut out,
        ".tile:hover",
        &[
            ("background-color", "var(--surface-s2)"),
            ("border-color", "var(--outline-soft)"),
            (
                "box-shadow",
                &format!(
                    "0 {} {} var(--shadow-soft)",
                    px(dims.space_50),
                    px(dims.space_150)
                ),
            ),
        ],
    );
    rule(
        &mut out,
        ".tile.selected",
        &[
            ("border-color", "var(--surface-primary-s0)"),
            ("border-width", "2px"),
        ],
    );
    rule(
        &mut out,
        ".tile.selected:hover",
        &[
            ("border-color", "var(--surface-primary-s2)"),
            (
                "box-shadow",
                &format!(
                    "0 {} {} var(--shadow-soft)",
                    px(dims.space_50),
                    px(dims.space_150)
                ),
            ),
        ],
    );
    // Muted tile variant — secondary card with warmer off-white background.
    rule(
        &mut out,
        ".tile.muted",
        &[("background-color", "var(--surface-s2)")],
    );
    // Small icon tile (36x36) with muted background — secondary action cards.
    rule(
        &mut out,
        ".surface-muted-tile",
        &[
            ("background-color", "var(--surface-s2)"),
            ("border-color", "var(--outline-subtle)"),
            ("border-width", "1px"),
            ("border-radius", &px(dims.radius_75)),
        ],
    );
    // Success-soft badge background — for "Connected" chip on active tile.
    rule(
        &mut out,
        ".success-soft",
        &[
            ("background-color", "var(--surface-success-s4)"),
            ("color", "var(--on-surface-success-default)"),
            ("border-radius", &px(dims.radius_50)),
        ],
    );

    // ── Table ──
    rule(
        &mut out,
        ".table",
        &[("border-color", "var(--outline-subtle)")],
    );
    rule(
        &mut out,
        ".table-header",
        &[
            ("background-color", "transparent"),
            ("color", "var(--text-soft)"),
        ],
    );
    rule(
        &mut out,
        ".table-header:hover",
        &[
            ("background-color", "var(--outline-subtle)"),
            ("color", "var(--text)"),
        ],
    );
    rule(
        &mut out,
        ".table-row",
        &[
            ("background-color", "transparent"),
            ("color", "var(--text-default)"),
        ],
    );
    rule(
        &mut out,
        ".table-row:hover",
        &[("background-color", "var(--surface-s1)")],
    );
    rule(
        &mut out,
        ".table-row.selected",
        &[
            ("background-color", "var(--surface-primary-s0)"),
            ("color", "var(--on-surface-primary-default)"),
        ],
    );
    rule(
        &mut out,
        ".table-row.selected:hover",
        &[("background-color", "var(--surface-primary-s2)")],
    );
    rule(
        &mut out,
        ".table-footer",
        &[
            ("background-color", "transparent"),
            ("color", "var(--text-soft)"),
        ],
    );
    rule(
        &mut out,
        ".table-frozen",
        &[("background-color", "var(--surface-s1)")],
    );

    // ── App containers (desktop app layout) ──
    rule(
        &mut out,
        ".surface",
        &[
            ("background-color", "var(--surface-s0)"),
            ("color", "var(--text-default)"),
        ],
    );
    rule(
        &mut out,
        ".surface-raised",
        &[
            ("background-color", "var(--surface-s2)"),
            ("color", "var(--text-default)"),
        ],
    );
    rule(
        &mut out,
        ".sidebar",
        &[
            ("background-color", "var(--surface-s1)"),
            ("color", "var(--text-default)"),
        ],
    );
    rule(
        &mut out,
        ".sidebar-item",
        &[
            ("background-color", "transparent"),
            ("color", "var(--text-muted)"),
            ("border-radius", "0"),
            ("accent-color", "var(--text-faint)"),
        ],
    );
    rule(
        &mut out,
        ".sidebar-item:hover",
        &[
            ("background-color", "var(--outline-subtle)"),
            ("color", "var(--text-default)"),
            ("accent-color", "var(--text-soft)"),
        ],
    );
    rule(
        &mut out,
        ".sidebar-item:active",
        &[("background-color", "var(--outline-soft)")],
    );
    rule(
        &mut out,
        ".sidebar-item.active",
        &[
            ("background-color", "var(--surface-s2)"),
            ("color", "var(--text-default)"),
        ],
    );
    rule(
        &mut out,
        ".toolbar",
        &[
            ("background-color", "var(--surface-s0)"),
            ("color", "var(--text-default)"),
            ("border-color", "var(--outline-subtle)"),
        ],
    );
    rule(
        &mut out,
        ".popup",
        &[
            ("background-color", "var(--surface-s2)"),
            ("color", "var(--text-default)"),
            ("border-color", "var(--outline-soft)"),
            ("border-radius", "8"),
            ("box-shadow", "0 4px 12px rgba(0, 0, 0, 0.4)"),
        ],
    );
    rule(
        &mut out,
        ".status-bar",
        &[
            ("background-color", "var(--surface-s1)"),
            ("color", "var(--text-dim)"),
            ("border-color", "var(--outline-subtle)"),
        ],
    );
    rule(
        &mut out,
        ".stats",
        &[
            ("background-color", "var(--surface-s0)"),
            ("color", "var(--text-dim)"),
            ("border-color", "var(--outline-subtle)"),
        ],
    );
    rule(&mut out, ".viewport", &[("background-color", "#000000")]);
    rule(
        &mut out,
        ".tab",
        &[
            ("background-color", "transparent"),
            ("color", "var(--text-soft)"),
            ("border-radius", &px(dims.radius_75)),
        ],
    );
    rule(
        &mut out,
        ".tab:hover",
        &[
            ("background-color", "var(--surface-s1)"),
            ("color", "var(--text-default)"),
        ],
    );
    rule(
        &mut out,
        ".tab.active",
        &[
            ("background-color", "var(--surface-s3)"),
            ("color", "var(--text)"),
        ],
    );

    // ── Chat bubbles ──
    rule(
        &mut out,
        ".chat-local",
        &[
            ("background-color", "var(--surface-primary-s0)"),
            ("color", "var(--on-surface-primary-default)"),
            ("border-radius", &px(dims.radius_100)),
        ],
    );
    // TODO(merge): review chat-remote alongside per-size radius rules below
    // (HEAD app-container styles + origin/main per-size .sz-* compose at the
    // same insertion point — both kept; verify there is no override conflict).
    rule(
        &mut out,
        ".chat-remote",
        &[
            ("background-color", "var(--surface-s2)"),
            ("color", "var(--text-default)"),
            ("border-radius", &px(dims.radius_100)),
        ],
    );

    // Padded min-heights for interactive controls.
    let padded_mh_md = px(2.0 * dims.space_100 + dims.font_label_large);
    let padded_mh_sm = px(2.0 * dims.space_75 + dims.font_label_medium);
    let padded_mh_xs = px(2.0 * dims.space_50 + dims.font_label_small);
    // Input/select min-widths: ~2 char widths + horizontal padding.
    let input_mw_md = px((dims.font_label_large * 1.2 + 2.0 * dims.space_200).ceil());
    let input_mw_sm = px((dims.font_label_medium * 1.2 + 2.0 * dims.space_150).ceil());
    let input_mw_xs = px((dims.font_label_small * 1.2 + 2.0 * dims.space_100).ceil());

    // ── Button baseline offset per type × size ──
    // Compensates for iced text baseline positioning.
    rule(&mut out, ".btn-label.sz-md", &[("baseline-offset", "2px")]);
    rule(&mut out, ".btn-label.sz-sm", &[("baseline-offset", "2px")]);
    rule(&mut out, ".btn-label.sz-xs", &[("baseline-offset", "2px")]);
    rule(
        &mut out,
        ".btn-icon-label.sz-md",
        &[("baseline-offset", "2px")],
    );
    rule(
        &mut out,
        ".btn-icon-label.sz-sm",
        &[("baseline-offset", "2px")],
    );
    rule(
        &mut out,
        ".btn-icon-label.sz-xs",
        &[("baseline-offset", "2px")],
    );
    rule(&mut out, ".btn-icon.sz-md", &[("baseline-offset", "0")]);
    rule(&mut out, ".btn-icon.sz-sm", &[("baseline-offset", "0")]);
    rule(&mut out, ".btn-icon.sz-xs", &[("baseline-offset", "0")]);

    // ── Alignment utility classes ──
    rule(&mut out, ".halign-center", &[("text-align", "center")]);
    rule(&mut out, ".halign-left", &[("text-align", "left")]);
    rule(&mut out, ".halign-right", &[("text-align", "right")]);
    rule(&mut out, ".valign-center", &[("vertical-align", "center")]);
    rule(&mut out, ".valign-top", &[("vertical-align", "top")]);
    rule(&mut out, ".valign-bottom", &[("vertical-align", "bottom")]);

    // ── Per-size compound selectors (border-radius + min-width + min-height) ──
    // Specificity (0,2) beats the base component rules at (0,1).

    // Buttons: uniform label width + padded min-height + radius + padding-offset
    rule(
        &mut out,
        ".button.sz-md",
        &[
            ("border-radius", "var(--radius-100)"),
            ("min-width", "100px"),
            ("min-height", &padded_mh_md),
            ("padding-offset", "1px"),
        ],
    );
    rule(
        &mut out,
        ".button.sz-sm",
        &[
            ("border-radius", "var(--radius-75)"),
            ("min-width", "80px"),
            ("min-height", &padded_mh_sm),
        ],
    );
    rule(
        &mut out,
        ".button.sz-xs",
        &[
            ("border-radius", "var(--radius-50)"),
            ("min-height", &padded_mh_xs),
        ],
    );

    // Shape overrides — must come after .button.sz-* to win by source order.
    rule(
        &mut out,
        ".button.round",
        &[("border-radius", &px(dims.radius_infinite))],
    );
    rule(
        &mut out,
        ".button.pill",
        &[("border-radius", &px(dims.radius_infinite))],
    );

    // Inputs, selects, editors, select-menus: radius + min-width + min-height per size
    for cmp in ["input", "select", "editor", "select-menu"] {
        rule(
            &mut out,
            &format!(".{cmp}.sz-md"),
            &[
                ("border-radius", "var(--radius-100)"),
                ("min-width", &input_mw_md),
                ("min-height", &padded_mh_md),
            ],
        );
        rule(
            &mut out,
            &format!(".{cmp}.sz-sm"),
            &[
                ("border-radius", "var(--radius-75)"),
                ("min-width", &input_mw_sm),
                ("min-height", &padded_mh_sm),
            ],
        );
        rule(
            &mut out,
            &format!(".{cmp}.sz-xs"),
            &[
                ("border-radius", "var(--radius-50)"),
                ("min-width", &input_mw_xs),
                ("min-height", &padded_mh_xs),
            ],
        );
    }
    // Checkboxes are visually tiny to begin with, so small/tiny use the
    // smallest radius token. Medium stays at the base r-50.
    rule(
        &mut out,
        ".checkbox.sz-md",
        &[("border-radius", "var(--radius-50)")],
    );
    rule(
        &mut out,
        ".checkbox.sz-sm",
        &[("border-radius", "var(--radius-25)")],
    );
    rule(
        &mut out,
        ".checkbox.sz-xs",
        &[("border-radius", "var(--radius-25)")],
    );

    // ── Menu container: tighter padding + gap than .select-menu default ──
    // Composes with .select-menu (bg/border/shadow). Padding applied by
    // icss::widgets::Menu via the `.menu` class.
    rule(
        &mut out,
        ".menu",
        &[
            ("padding-v", "var(--space-100)"),
            ("padding-h", "var(--space-100)"),
            ("gap", "var(--space-50)"),
        ],
    );

    // ── Typography surface contexts ──
    rule(
        &mut out,
        ".typo-surface",
        &[
            ("background-color", "var(--surface-s0)"),
            ("color", "var(--text-default)"),
            ("border-radius", &px(dims.radius_100)),
        ],
    );
    rule(
        &mut out,
        ".typo-surface-raised",
        &[
            ("background-color", "var(--surface-s2)"),
            ("color", "var(--text-default)"),
            ("border-radius", &px(dims.radius_100)),
        ],
    );
    rule(
        &mut out,
        ".typo-surface-s3",
        &[
            ("background-color", "var(--surface-s3)"),
            ("color", "var(--text-default)"),
            ("border-radius", &px(dims.radius_100)),
        ],
    );
    rule(
        &mut out,
        ".typo-surface-s4",
        &[
            ("background-color", "var(--surface-s4)"),
            ("color", "var(--text-default)"),
            ("border-radius", &px(dims.radius_100)),
        ],
    );
    rule(
        &mut out,
        ".typo-surface-s5",
        &[
            ("background-color", "var(--surface-s5)"),
            ("color", "var(--text-default)"),
            ("border-radius", &px(dims.radius_100)),
        ],
    );
    rule(
        &mut out,
        ".typo-tint",
        &[
            ("background-color", "var(--surface-tint-s0)"),
            ("color", "var(--on-surface-tint)"),
            ("border-radius", &px(dims.radius_100)),
        ],
    );
    rule(
        &mut out,
        ".typo-dark-tint",
        &[
            ("background-color", "var(--surface-dark-tint-s0)"),
            ("color", "var(--on-surface-dark-tint)"),
            ("border-radius", &px(dims.radius_100)),
        ],
    );
    rule(
        &mut out,
        ".typo-black",
        &[
            ("background-color", "var(--surface-black-s0)"),
            ("color", "var(--on-surface-black)"),
            ("border-radius", &px(dims.radius_100)),
        ],
    );
    rule(
        &mut out,
        ".typo-primary",
        &[
            ("background-color", "var(--surface-primary-s0)"),
            ("color", "var(--on-surface-primary-default)"),
            ("border-radius", &px(dims.radius_100)),
        ],
    );
    rule(
        &mut out,
        ".typo-primary-container",
        &[
            ("background-color", "var(--surface-primary-container-s0)"),
            ("color", "var(--on-surface-primary-container-default)"),
            ("border-radius", &px(dims.radius_100)),
        ],
    );

    // ── Text color samples (for color contrast showcase) ──
    rule(
        &mut out,
        ".color-surface",
        &[
            ("background-color", "var(--surface-s0)"),
            ("color", "var(--text)"),
            ("border-radius", &px(dims.radius_100)),
        ],
    );
    rule(
        &mut out,
        ".color-tint",
        &[
            ("background-color", "var(--surface-tint-s0)"),
            ("color", "var(--on-surface-tint)"),
            ("border-radius", &px(dims.radius_100)),
        ],
    );
    rule(
        &mut out,
        ".color-dark-tint",
        &[
            ("background-color", "var(--surface-dark-tint-s0)"),
            ("color", "var(--on-surface-dark-tint)"),
            ("border-radius", &px(dims.radius_100)),
        ],
    );
    rule(
        &mut out,
        ".color-primary",
        &[
            ("background-color", "var(--surface-primary-s0)"),
            ("color", "var(--on-surface-primary-default)"),
            ("border-radius", &px(dims.radius_100)),
        ],
    );
    rule(
        &mut out,
        ".color-black",
        &[
            ("background-color", "var(--surface-black-s0)"),
            ("color", "var(--on-surface-black)"),
            ("border-radius", &px(dims.radius_100)),
        ],
    );

    // ═══ Text utility classes ═══════════════════════════════════════════
    // Size + weight + default color. Compose with text color modifiers
    // below to override color. Usage: theme.text("...", &["title-small"])
    // or theme.text("Error", &["label-small", "text-danger"]).
    //
    // Per docs/theme-creation.md section 2 typography scale:
    //   headline: display / hero text, 300 light (≤30px) or 400 (>30px)
    //   title:    section headings, 600 semibold
    //   label:    UI control labels, 600 semibold
    //   body:     reading text, 400 regular

    // Headlines — display/hero text, soft color, light weight (300/400).
    rule(
        &mut out,
        ".headline-xlarge",
        &[
            ("font-size", "var(--font-headline-xlarge)"),
            ("color", "var(--text-soft)"),
            ("font-weight", "300"),
        ],
    );
    rule(
        &mut out,
        ".headline-large",
        &[
            ("font-size", "var(--font-headline-large)"),
            ("color", "var(--text-soft)"),
            ("font-weight", "300"),
        ],
    );
    rule(
        &mut out,
        ".headline-medium",
        &[
            ("font-size", "var(--font-headline-medium)"),
            ("color", "var(--text-soft)"),
            ("font-weight", "400"),
        ],
    );
    rule(
        &mut out,
        ".headline-small",
        &[
            ("font-size", "var(--font-headline-small)"),
            ("color", "var(--text-soft)"),
            ("font-weight", "400"),
        ],
    );
    rule(
        &mut out,
        ".headline-micro",
        &[
            ("font-size", "var(--font-headline-micro)"),
            ("color", "var(--text-soft)"),
            ("font-weight", "400"),
        ],
    );

    // Titles — subsection headings, soft color, semibold.
    rule(
        &mut out,
        ".title-large",
        &[
            ("font-size", "var(--font-title-large)"),
            ("color", "var(--text-soft)"),
            ("font-weight", "600"),
        ],
    );
    rule(
        &mut out,
        ".title-medium",
        &[
            ("font-size", "var(--font-title-medium)"),
            ("color", "var(--text-soft)"),
            ("font-weight", "600"),
        ],
    );
    rule(
        &mut out,
        ".title-small",
        &[
            ("font-size", "var(--font-title-small)"),
            ("color", "var(--text-soft)"),
            ("font-weight", "600"),
        ],
    );

    // Labels — form field labels, soft color, semibold.
    rule(
        &mut out,
        ".label-large",
        &[
            ("font-size", "var(--font-label-large)"),
            ("color", "var(--text-soft)"),
            ("font-weight", "600"),
        ],
    );
    rule(
        &mut out,
        ".label-medium",
        &[
            ("font-size", "var(--font-label-medium)"),
            ("color", "var(--text-soft)"),
            ("font-weight", "600"),
        ],
    );
    rule(
        &mut out,
        ".label-small",
        &[
            ("font-size", "var(--font-label-small)"),
            ("color", "var(--text-soft)"),
            ("font-weight", "600"),
        ],
    );
    rule(
        &mut out,
        ".label-micro",
        &[
            ("font-size", "var(--font-label-micro)"),
            ("color", "var(--text-soft)"),
            ("font-weight", "600"),
        ],
    );

    // Body
    rule(
        &mut out,
        ".body-large",
        &[
            ("font-size", "var(--font-body-large)"),
            ("color", "var(--text-default)"),
            ("font-weight", "400"),
        ],
    );
    rule(
        &mut out,
        ".body-medium",
        &[
            ("font-size", "var(--font-body-medium)"),
            ("color", "var(--text-default)"),
            ("font-weight", "400"),
        ],
    );
    rule(
        &mut out,
        ".body-small",
        &[
            ("font-size", "var(--font-body-small)"),
            ("color", "var(--text-default)"),
            ("font-weight", "400"),
        ],
    );
    rule(
        &mut out,
        ".body-micro",
        &[
            ("font-size", "var(--font-body-micro)"),
            ("color", "var(--text-soft)"),
            ("font-weight", "400"),
        ],
    );

    // Caption — small inline secondary info (dim by default)
    rule(
        &mut out,
        ".caption",
        &[
            ("font-size", "var(--font-label-micro)"),
            ("color", "var(--text-soft)"),
            ("font-weight", "400"),
        ],
    );
    // Eyebrow — small uppercase section label (600 weight, tracking).
    rule(
        &mut out,
        ".eyebrow",
        &[
            ("font-size", "var(--font-label-micro)"),
            ("color", "var(--text-faint)"),
            ("font-weight", "600"),
            ("text-transform", "uppercase"),
            ("letter-spacing", "0.06em"),
        ],
    );

    // ═══ Text color modifier classes ════════════════════════════════════
    // Color only. Compose with any text size class.
    // Neutral text levels (on neutral surface)
    rule(
        &mut out,
        ".text-default",
        &[("color", "var(--text-default)")],
    );
    rule(&mut out, ".text-soft", &[("color", "var(--text-soft)")]);
    rule(&mut out, ".text-muted", &[("color", "var(--text-muted)")]);
    rule(&mut out, ".text-faint", &[("color", "var(--text-faint)")]);
    rule(
        &mut out,
        ".text-disabled-color",
        &[("color", "var(--text-disabled)")],
    );
    // On-surface text modifiers (for use on colored surfaces)
    rule(
        &mut out,
        ".text-on-primary",
        &[("color", "var(--on-surface-primary-default)")],
    );
    rule(
        &mut out,
        ".text-on-primary-soft",
        &[("color", "var(--on-surface-primary-soft)")],
    );
    rule(
        &mut out,
        ".text-on-secondary",
        &[("color", "var(--on-surface-secondary-default)")],
    );
    rule(
        &mut out,
        ".text-on-secondary-soft",
        &[("color", "var(--on-surface-secondary-soft)")],
    );
    rule(
        &mut out,
        ".text-on-tertiary",
        &[("color", "var(--on-surface-tertiary-default)")],
    );
    rule(
        &mut out,
        ".text-on-tertiary-soft",
        &[("color", "var(--on-surface-tertiary-soft)")],
    );
    // Hue-colored text (accent on neutral surface)
    rule(
        &mut out,
        ".text-primary",
        &[("color", "var(--surface-primary-s0)")],
    );
    rule(
        &mut out,
        ".text-secondary",
        &[("color", "var(--surface-secondary-s0)")],
    );
    rule(
        &mut out,
        ".text-tertiary",
        &[("color", "var(--surface-tertiary-s0)")],
    );
    rule(
        &mut out,
        ".text-quaternary",
        &[("color", "var(--surface-quaternary-s0)")],
    );
    rule(
        &mut out,
        ".text-link",
        &[("color", "var(--surface-link-s0)")],
    );
    rule(
        &mut out,
        ".text-success",
        &[("color", "var(--surface-success-s0)")],
    );
    rule(
        &mut out,
        ".text-danger",
        &[("color", "var(--surface-danger-s0)")],
    );
    rule(
        &mut out,
        ".text-warning",
        &[("color", "var(--surface-warning-s0)")],
    );

    // ═══ Layout / scaffolding classes ═══════════════════════════════════
    // Gap-only classes (for theme.row / theme.column). Direction is implied
    // by the helper — `.stack` and `.row` both carry space-100 gap but read
    // semantically as vertical / horizontal.
    rule(&mut out, ".stack", &[("gap", "var(--space-100)")]);
    rule(&mut out, ".stack-tight", &[("gap", "var(--space-75)")]);
    rule(&mut out, ".stack-loose", &[("gap", "var(--space-200)")]);
    rule(&mut out, ".row", &[("gap", "var(--space-100)")]);
    rule(&mut out, ".row-tight", &[("gap", "var(--space-75)")]);
    rule(&mut out, ".row-loose", &[("gap", "var(--space-200)")]);
    rule(&mut out, ".cluster", &[("gap", "var(--space-50)")]);

    // Padding + gap classes (for theme.frame — content-taking container).
    // `.page-body` — root page chrome
    rule(
        &mut out,
        ".page-body",
        &[
            ("padding-v", "var(--space-200)"),
            ("padding-h", "var(--space-200)"),
            ("gap", "var(--space-300)"),
        ],
    );
    // `.section-body` — padding inside a `.section` card
    rule(
        &mut out,
        ".section-body",
        &[
            ("padding-v", "var(--space-200)"),
            ("padding-h", "var(--space-200)"),
            ("gap", "var(--space-150)"),
        ],
    );
    // `.subsection` — vertical block inside a section (gap only, no padding)
    rule(&mut out, ".subsection", &[("gap", "var(--space-100)")]);
    // Label + control rows
    rule(&mut out, ".field-row", &[("gap", "var(--space-100)")]);
    rule(&mut out, ".field-col", &[("gap", "var(--space-50)")]);

    // ── Standard form layout ──
    // sp-200 padding, sp-150 gap between form rows.
    rule(
        &mut out,
        ".form",
        &[
            ("padding-v", "var(--space-200)"),
            ("padding-h", "var(--space-200)"),
            ("gap", "var(--space-150)"),
        ],
    );
    // Horizontal form row: label (fixed) + input (fill) + help icon.
    rule(&mut out, ".form-row", &[("gap", "var(--space-100)")]);
    // Vertical checkbox/toggle group below a form row.
    rule(&mut out, ".form-group", &[("gap", "var(--space-75)")]);

    // ── Primitives page — color swatches ──
    let r50 = px(dims.radius_50);
    let outline_swatch = |out: &mut String, cls: &str, border: &str| {
        rule(
            out,
            cls,
            &[
                ("border-width", "2px"),
                ("border-color", border),
                ("border-radius", &r50),
            ],
        );
    };

    // Neutral surface swatches (s0-s5)
    for i in 0..=5 {
        let cls = format!(".sw-surface-{i}");
        let bg = format!("var(--surface-s{i})");
        rule(
            &mut out,
            &cls,
            &[("background-color", &bg), ("border-radius", &r50)],
        );
    }
    // Neutral on-surface text swatches
    {
        let swatch = |out: &mut String, cls: &str, bg: &str| {
            rule(
                out,
                cls,
                &[("background-color", bg), ("border-radius", &r50)],
            );
        };
        swatch(&mut out, ".sw-on-surface", "var(--text)");
        swatch(&mut out, ".sw-on-surface-default", "var(--text-default)");
        swatch(&mut out, ".sw-on-surface-soft", "var(--text-soft)");
        swatch(&mut out, ".sw-on-surface-dim", "var(--text-dim)");
        swatch(&mut out, ".sw-on-surface-muted", "var(--text-muted)");
        swatch(&mut out, ".sw-on-surface-faint", "var(--text-faint)");
        swatch(&mut out, ".sw-on-surface-disabled", "var(--text-disabled)");
    }

    // Surface families via helper
    emit_family_swatches(&mut out, "surface-tint", &r50);
    emit_family_swatches(&mut out, "surface-dark-tint", &r50);
    emit_family_swatches(&mut out, "surface-black", &r50);
    emit_family_swatches(&mut out, "surface-primary", &r50);
    emit_family_swatches(&mut out, "surface-primary-container", &r50);
    emit_family_swatches(&mut out, "surface-secondary", &r50);
    emit_family_swatches(&mut out, "surface-secondary-container", &r50);
    emit_family_swatches(&mut out, "surface-tertiary", &r50);
    emit_family_swatches(&mut out, "surface-tertiary-container", &r50);
    emit_family_swatches(&mut out, "surface-quaternary", &r50);
    emit_family_swatches(&mut out, "surface-quaternary-container", &r50);
    emit_family_swatches(&mut out, "surface-success", &r50);
    emit_family_swatches(&mut out, "surface-success-container", &r50);
    emit_family_swatches(&mut out, "surface-danger", &r50);
    emit_family_swatches(&mut out, "surface-danger-container", &r50);
    emit_family_swatches(&mut out, "surface-warning", &r50);
    emit_family_swatches(&mut out, "surface-warning-container", &r50);

    // Outline swatches (as borders)
    outline_swatch(&mut out, ".sw-outline-subtle", "var(--outline-subtle-hex)");
    outline_swatch(&mut out, ".sw-outline-soft", "var(--outline-soft-hex)");
    outline_swatch(&mut out, ".sw-outline-middle", "var(--outline-middle)");
    outline_swatch(&mut out, ".sw-outline-strong", "var(--outline-strong)");
    outline_swatch(&mut out, ".sw-outline-heavy", "var(--outline-heavy)");
    outline_swatch(&mut out, ".sw-outline-solid", "var(--outline-solid)");

    // Accent on neutral swatches
    {
        let swatch = |out: &mut String, cls: &str, bg: &str| {
            rule(
                out,
                cls,
                &[("background-color", bg), ("border-radius", &r50)],
            );
        };
        swatch(&mut out, ".sw-accent-primary", "var(--surface-primary-s0)");
        swatch(
            &mut out,
            ".sw-accent-secondary",
            "var(--surface-secondary-s0)",
        );
        swatch(
            &mut out,
            ".sw-accent-tertiary",
            "var(--surface-tertiary-s0)",
        );
        swatch(
            &mut out,
            ".sw-accent-quaternary",
            "var(--surface-quaternary-s0)",
        );
        swatch(&mut out, ".sw-accent-link", "var(--surface-link-s0)");
        swatch(&mut out, ".sw-accent-success", "var(--surface-success-s0)");
        swatch(&mut out, ".sw-accent-danger", "var(--surface-danger-s0)");
        swatch(&mut out, ".sw-accent-warning", "var(--surface-warning-s0)");

        // Shadow color swatches
        swatch(&mut out, ".sw-shadow", "var(--shadow)");
        swatch(&mut out, ".sw-shadow-medium", "var(--shadow-medium)");
        swatch(&mut out, ".sw-shadow-soft", "var(--shadow-soft)");
    }

    // Alias for spacing bars
    rule(
        &mut out,
        ".primary-swatch",
        &[
            ("background-color", "var(--surface-primary-s0)"),
            ("border-radius", &r50),
        ],
    );

    // Radius demo container
    rule(
        &mut out,
        ".radius-demo",
        &[
            ("border-color", "var(--outline-soft)"),
            ("border-width", "1px"),
        ],
    );

    // Shadow demo boxes — 1px no blur
    rule(
        &mut out,
        ".sh-1px-soft",
        &[
            ("background-color", "var(--surface-s0)"),
            ("border-radius", &px(dims.radius_75)),
            ("box-shadow", "0 1px 0 var(--shadow-soft)"),
        ],
    );
    rule(
        &mut out,
        ".sh-1px-medium",
        &[
            ("background-color", "var(--surface-s0)"),
            ("border-radius", &px(dims.radius_75)),
            ("box-shadow", "0 1px 0 var(--shadow-medium)"),
        ],
    );
    rule(
        &mut out,
        ".sh-1px-default",
        &[
            ("background-color", "var(--surface-s0)"),
            ("border-radius", &px(dims.radius_75)),
            ("box-shadow", "0 1px 0 var(--shadow)"),
        ],
    );
    // 1px with blur
    rule(
        &mut out,
        ".shadow-soft-demo",
        &[
            ("background-color", "var(--surface-s0)"),
            ("border-radius", &px(dims.radius_75)),
            (
                "box-shadow",
                &format!("0 1px {} var(--shadow-soft)", px(dims.space_50)),
            ),
        ],
    );
    rule(
        &mut out,
        ".shadow-medium-demo",
        &[
            ("background-color", "var(--surface-s0)"),
            ("border-radius", &px(dims.radius_75)),
            (
                "box-shadow",
                &format!("0 1px {} var(--shadow-medium)", px(dims.space_50)),
            ),
        ],
    );
    rule(
        &mut out,
        ".shadow-demo",
        &[
            ("background-color", "var(--surface-s0)"),
            ("border-radius", &px(dims.radius_75)),
            (
                "box-shadow",
                &format!("0 1px {} var(--shadow)", px(dims.space_50)),
            ),
        ],
    );

    // Elevated shadows — 3 color variants x 5 blur levels
    let blur_levels: &[(&str, f32, f32)] = &[
        ("50", dims.space_25, dims.space_50),
        ("75", dims.space_50, dims.space_75),
        ("100", dims.space_50, dims.space_100),
        ("150", dims.space_75, dims.space_150),
        ("200", dims.space_100, dims.space_200),
    ];
    let shadow_colors: &[(&str, &str)] = &[
        ("soft", "shadow-soft"),
        ("medium", "shadow-medium"),
        ("default", "shadow"),
    ];
    for (blur_name, y_off, blur) in blur_levels {
        for (color_name, color_var) in shadow_colors {
            let cls = format!(".sh-elevated-{blur_name}-{color_name}");
            rule(
                &mut out,
                &cls,
                &[
                    ("background-color", "var(--surface-s0)"),
                    ("border-radius", &px(dims.radius_75)),
                    (
                        "box-shadow",
                        &format!("0 {} {} var(--{color_var})", px(*y_off), px(*blur)),
                    ),
                ],
            );
        }
    }
    // Legacy elevated classes (soft color, for backward compat)
    rule(
        &mut out,
        ".sh-elevated-50",
        &[
            ("background-color", "var(--surface-s0)"),
            ("border-radius", &px(dims.radius_75)),
            (
                "box-shadow",
                &format!(
                    "0 {} {} var(--shadow-soft)",
                    px(dims.space_25),
                    px(dims.space_50)
                ),
            ),
        ],
    );
    rule(
        &mut out,
        ".sh-elevated-100",
        &[
            ("background-color", "var(--surface-s0)"),
            ("border-radius", &px(dims.radius_75)),
            (
                "box-shadow",
                &format!(
                    "0 {} {} var(--shadow-soft)",
                    px(dims.space_50),
                    px(dims.space_100)
                ),
            ),
        ],
    );
    rule(
        &mut out,
        ".sh-elevated-150",
        &[
            ("background-color", "var(--surface-s0)"),
            ("border-radius", &px(dims.radius_75)),
            (
                "box-shadow",
                &format!(
                    "0 {} {} var(--shadow-medium)",
                    px(dims.space_75),
                    px(dims.space_150)
                ),
            ),
        ],
    );
    rule(
        &mut out,
        ".sh-elevated-200",
        &[
            ("background-color", "var(--surface-s0)"),
            ("border-radius", &px(dims.radius_75)),
            (
                "box-shadow",
                &format!(
                    "0 {} {} var(--shadow)",
                    px(dims.space_100),
                    px(dims.space_200)
                ),
            ),
        ],
    );

    // ── Size-keyed border radius ─────────────────────────────────────────
    // Emitted after all component rules so that — at equal specificity —
    // these win on source order. Any control whose style class list also
    // includes a sz-* class picks up its size-appropriate radius:
    //   sz-md → r-100   sz-sm → r-75   sz-xs → r-50
    rule(
        &mut out,
        ".sz-md",
        &[("border-radius", &px(dims.radius_100))],
    );
    rule(
        &mut out,
        ".sz-sm",
        &[("border-radius", &px(dims.radius_75))],
    );
    rule(
        &mut out,
        ".sz-xs",
        &[("border-radius", &px(dims.radius_50))],
    );

    out
}

fn css_var(out: &mut String, name: &str, value: &str) {
    out.push_str(&format!("    --{name}: {value};\n"));
}

fn rule(out: &mut String, selector: &str, declarations: &[(&str, &str)]) {
    out.push_str(selector);
    out.push_str(" {\n");
    for (prop, val) in declarations {
        out.push_str(&format!("    {prop}: {val};\n"));
    }
    out.push_str("}\n\n");
}

fn px(v: f32) -> String {
    let i = v.round() as i32;
    if i == 0 { "0".into() } else { format!("{i}px") }
}
