//! Generates `.icss` theme strings from `ThemeVars` via the icss engine.

use crate::ThemeVars;

/// Sidebar theme (static, not generated by the engine).
pub const SIDEBAR_THEME: &str = r#"
:root {
    --sidebar-bg: #16162e;
    --sidebar-input-bg: #ffffff0d;
    --sidebar-border: #ffffff15;
    --sidebar-text: #cccccc;
}
.sidebar {
    background-color: var(--sidebar-bg);
    color: var(--sidebar-text);
}
.sidebar-input {
    background-color: var(--sidebar-input-bg);
    color: #eaeaea;
    border-radius: 4px;
    border-width: 1px;
    border-color: var(--sidebar-border);
    placeholder-color: #555555;
}
.sidebar-input:focus {
    border-color: #0f3460;
}
"#;

/// Build the engine inputs from the current showcase vars.
fn theme_inputs(vars: &ThemeVars) -> icss::engine::ThemeInputs {
    // Empty override → None → engine derives from chromatic colors.
    let opt_hex = |s: &str| {
        let s = s.trim();
        if s.is_empty() {
            None
        } else {
            Some(s.to_string())
        }
    };
    icss::engine::ThemeInputs {
        primary: vars.primary.clone(),
        secondary: vars.secondary.clone(),
        tertiary: vars.tertiary.clone(),
        quaternary: vars.quaternary.clone(),
        neutral: vars.neutral.clone(),
        link: vars.link.clone(),
        increment: vars.increment,
        font_increment: vars.font_increment,
        radius_factor: vars.radius_factor,
        dark_mode: vars.dark_mode,
        surface_lightness: Some(vars.surface_lightness as u8),
        gamma: Some(vars.gamma),
        text_spread: Some(vars.text_spread),
        success_override: opt_hex(&vars.success_override),
        danger_override: opt_hex(&vars.danger_override),
        warning_override: opt_hex(&vars.warning_override),
    }
}

/// Generate a full `.icss` theme for the live preview, and — when
/// `write_artifacts` is true — emit fresh `theme-dark.icss` /
/// `theme-light.icss` files next to the showcase binary. Updates derived
/// signal-color fields in `vars` in place.
///
/// Writing the generated themes to disk is what `cargo run -p icss-showcase`
/// produces as its on-disk output — pair it with `showcase-vars.conf`
/// (written by `persist::save`) to capture a complete theme snapshot. The
/// "Save .icss" toggle in the tab bar passes `write_artifacts = false` so a
/// user can experiment with the visuals without touching the files on disk.
pub fn generate_icss(vars: &mut ThemeVars, write_artifacts: bool) -> icss::engine::ThemeOutput {
    let inputs = theme_inputs(vars);
    let output = icss::engine::generate(&inputs);

    vars.derived_success = output.derived_success.clone();
    vars.derived_danger = output.derived_danger.clone();
    vars.derived_warning = output.derived_warning.clone();

    if write_artifacts {
        write_theme_artifacts(&inputs);
    }

    output
}

/// Generate dark + light variants from the same chromatic inputs and write
/// them next to the showcase executable as `theme-dark.icss` and
/// `theme-light.icss`. Errors are logged at WARN — never fatal, since the
/// live preview doesn't depend on the file write.
fn write_theme_artifacts(inputs: &icss::engine::ThemeInputs) {
    use icss::engine::semantic::{Mode, default_surface_lightness};

    let mut dark = inputs.clone();
    dark.dark_mode = true;
    dark.surface_lightness = Some(default_surface_lightness(Mode::Dark));
    let dark_icss = icss::engine::generate(&dark).icss;

    let mut light = inputs.clone();
    light.dark_mode = false;
    light.surface_lightness = Some(default_surface_lightness(Mode::Light));
    let light_icss = icss::engine::generate(&light).icss;

    let dir = match std::env::current_exe()
        .ok()
        .and_then(|p| p.parent().map(std::path::Path::to_path_buf))
    {
        Some(d) => d,
        None => {
            tracing::warn!("[theme] cannot locate exe dir; skipping .icss write");
            return;
        }
    };

    if let Err(e) = std::fs::write(dir.join("theme-dark.icss"), &dark_icss) {
        tracing::warn!("[theme] write theme-dark.icss failed: {e}");
    }
    if let Err(e) = std::fs::write(dir.join("theme-light.icss"), &light_icss) {
        tracing::warn!("[theme] write theme-light.icss failed: {e}");
    }
}
