primary=#020EE4
secondary=#3DAAFA
tertiary=#C42451
quaternary=#064E56
neutral=#8B959B
link=#0D5A9E
increment=8
font_increment=9
radius_factor=1.6
font_family=sfpro
dark_mode=true
surface_lightness=4
gamma=0.65000004
text_spread=2.4
dark_surface_lightness=2
dark_gamma=0.6
dark_text_spread=2.4
light_surface_lightness=97
light_gamma=0.70000005
light_text_spread=2.3
success_override=#0CBD7D
danger_override=#F60F31
warning_override=
